services:
  db-dev:
    image: postgres:17-alpine
    container_name: ddbb_restaurant_management_dev
    environment:
      POSTGRES_DB: ddbb_restaurant_management_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    volumes:
      - pgdatadev:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdatadev:
