# Development Environment Configuration
# This profile is active during local development

# Server Configuration
server.servlet.context-path=/api 
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/ddbb_restaurant_management_dev?user=postgres&password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging Configuration - More verbose for development
logging.level.root=INFO
logging.level.com.restaurant_management=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Document API 
scalar.enabled=true
scalar.path=docs
scalar.url=http://localhost:8080/api/v3/api-docs

# Frontend URL for CORS - Development frontend
# Soporta lista separada por comas y patrones con wildcard (*)
frontend.url=${FRONTEND_URL:http://localhost:5173,http://10.25.3.*:5173,http://10.25.3.*:5174,http://187.77.239.28}

# Security - JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY:HOv8ZZYQX29Trpm60oaaQcOUTcavzqIE8wigYj35gRQ1+auhRhPUJqifA7PDFQLW2VNYE+nI8wWWdo8aqAHquw==}
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# Cookie settings
cookie.secure=false
cookie.same-site=Lax

# Development specific settings
spring.devtools.restart.enabled=true
