# Production Environment Configuration

# Server Configuration
server.servlet.context-path=/api
server.port=${PORT:8081}

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
logging.level.root=WARN
logging.level.com.restaurant_management=INFO
logging.level.org.springframework.web=WARN

# Document API
scalar.enabled=true
scalar.path=docs
scalar.url=${API_DOCS_URL:http://localhost:8080/api/v3/api-docs}

# Frontend URL for CORS
frontend.url=${FRONTEND_URL}

# Security - JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# Cookie settings
cookie.secure=true
cookie.same-site=None

# Production specific settings
spring.devtools.restart.enabled=false
