CREATE TABLE transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT          NOT NULL REFERENCES orders(id),
    user_id             BIGINT          REFERENCES users(id),
    total               NUMERIC(10,2)   NOT NULL,
    payment_method      VARCHAR(20)     NOT NULL,
    status              VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    transaction_date    TIMESTAMP       NOT NULL,
    reference           VARCHAR(255),
    date_created        TIMESTAMP,
    date_updated        TIMESTAMP,
    user_created        VARCHAR(100),
    user_updated        VARCHAR(100),
    CONSTRAINT chk_transactions_payment_method CHECK (payment_method IN ('YAPE', 'CASH', 'CREDITCARD')),
    CONSTRAINT chk_transactions_status         CHECK (status          IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')),
    CONSTRAINT chk_transactions_total          CHECK (total > 0)
);
