CREATE TABLE table_transfer_audit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT          NOT NULL REFERENCES orders(id),
    from_table_id   BIGINT          NOT NULL REFERENCES tables(id),
    to_table_id     BIGINT          NOT NULL REFERENCES tables(id),
    user_id         BIGINT          REFERENCES users(id),
    order_total     NUMERIC(10,2)   NOT NULL,
    transfer_date   TIMESTAMP       NOT NULL,
    date_created    TIMESTAMP,
    date_updated    TIMESTAMP,
    user_created    VARCHAR(100),
    user_updated    VARCHAR(100)
);
