CREATE TABLE product_variants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT          NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    name            VARCHAR(255)    NOT NULL,
    price           NUMERIC(10,2)   NOT NULL,
    is_available    BOOLEAN         NOT NULL DEFAULT TRUE,
    sort_order      INT             NOT NULL DEFAULT 0,
    date_created    TIMESTAMP,
    date_updated    TIMESTAMP,
    user_created    VARCHAR(100),
    user_updated    VARCHAR(100),
    CONSTRAINT chk_product_variants_price CHECK (price >= 0)
);

CREATE INDEX idx_product_variants_product_id ON product_variants(product_id);
