CREATE TABLE roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50)  NOT NULL UNIQUE,
    date_created TIMESTAMP,
    date_updated TIMESTAMP,
    user_created VARCHAR(100),
    user_updated VARCHAR(100),
    CONSTRAINT   chk_roles_name CHECK (name IN ('ADMIN', 'CASHIER', 'CHEF', 'WAITER'))
);
