CREATE TABLE refresh_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token           VARCHAR(512)    NOT NULL UNIQUE,
    user_id         BIGINT          NOT NULL REFERENCES users(id),
    expires_at      TIMESTAMP       NOT NULL,
    revoked_at      TIMESTAMP,
    date_created    TIMESTAMP,
    date_updated    TIMESTAMP,
    user_created    VARCHAR(100),
    user_updated    VARCHAR(100)
);
