CREATE TABLE products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)    NOT NULL,
    description     VARCHAR(500),
    image_url       VARCHAR(500),
    price           NUMERIC(10,2)   NOT NULL DEFAULT 0.00,
    cost            NUMERIC(10,2),
    is_available    BOOLEAN         NOT NULL DEFAULT TRUE,
    category_id     BIGINT          NOT NULL REFERENCES categories(id),
    date_created    TIMESTAMP,
    date_updated    TIMESTAMP,
    user_created    VARCHAR(100),
    user_updated    VARCHAR(100),
    CONSTRAINT chk_products_price CHECK (price >= 0)
);
