CREATE TABLE tables (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number          VARCHAR(50)     NOT NULL UNIQUE,
    capacity        INT,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    state           VARCHAR(20)     NOT NULL DEFAULT 'FREE',
    date_created    TIMESTAMP,
    date_updated    TIMESTAMP,
    user_created    VARCHAR(100),
    user_updated    VARCHAR(100),
    CONSTRAINT chk_tables_state    CHECK (state    IN ('FREE', 'OCCUPIED', 'RESERVED')),
    CONSTRAINT chk_tables_capacity CHECK (capacity IS NULL OR capacity > 0)
);
