CREATE TABLE order_code_sequence (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_value   BIGINT          NOT NULL DEFAULT 0,
    date_created    TIMESTAMP,
    date_updated    TIMESTAMP,
    user_created    VARCHAR(100),
    user_updated    VARCHAR(100)
);

INSERT INTO order_code_sequence (current_value) VALUES (0);
