CREATE TABLE order_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT          NOT NULL REFERENCES orders(id),
    product_id          BIGINT          NOT NULL REFERENCES products(id),
    quantity            INT             NOT NULL DEFAULT 0,
    unit_price          NUMERIC(10,2)   NOT NULL,
    sub_total           NUMERIC(10,2)   NOT NULL DEFAULT 0.00,
    notes               VARCHAR(255),
    is_takeaway         BOOLEAN         NOT NULL DEFAULT FALSE,
    takeaway_surcharge  NUMERIC(10,2)   NOT NULL DEFAULT 0.00,
    date_created        TIMESTAMP,
    date_updated        TIMESTAMP,
    user_created        VARCHAR(100),
    user_updated        VARCHAR(100),
    CONSTRAINT chk_order_items_quantity  CHECK (quantity > 0),
    CONSTRAINT chk_order_items_subtotal  CHECK (sub_total >= 0)
);
